name: Publish Docker Image to GHCR

on:
  push:
    tags:
      - 'v*' # Trigger on version tags, e.g., v1.0, v2.1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image to GHCR
      env:
        IMAGE_NAME: "ghcr.io/${{ github.repository }}"
      run: |
        # Define tags based on Git tag
        TAG="${GITHUB_REF#refs/tags/}"
        docker buildx build --platform linux/amd64,linux/arm64 \
          -t $IMAGE_NAME:$TAG \
          -t $IMAGE_NAME:latest \
          --push .

    - name: Log out from GitHub Container Registry
      run: docker logout ghcr.io
