name: Test Medium Publisher Action

on:
  pull_request:
    branches:
      - master
  push:
    paths:
      - ./**
      - .github/workflows/test-publish-action.yml
  workflow_dispatch:

jobs:
  test-medium-publisher:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a test Markdown file
      run: |
        mkdir -p content
        echo "# Test Article" > content/test-article.md
        echo "This is a test article for the Medium publisher action." >> content/test-article.md

    - name: Run Medium Publisher Action
      uses: carlspring/medium-publish-action@master
      with:
        medium_token: ${{ secrets.MEDIUM_TOKEN }}
        file_path: "content/test-article.md"
        publish_status: "draft"

    - name: Verify Action Output
      run: |
        echo "If no errors occurred, the test passed."
